[package]
name = "bundler-types"
version = "0.1.0"
edition = "2021"

[dependencies]
contracts = { path = "../contracts" }
ethers = "2.0.3"
serde = "1.0.163"
serde_json = "1.0.96"
thiserror = "1.0.40"
