[package]
name = "bunder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.3"
actix-web = "4.3.1"
contracts = {path = "../contracts"}

[[bin]]
name = "bundler"
path = "bin/bundler.rs"
